// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvj-yjwYCfvapVpwnp7YHdv3OA_viHT-I',
    appId: '1:324767521440:web:4d87e25d33aea527a187c5',
    messagingSenderId: '324767521440',
    projectId: 'crud-a8dfc',
    authDomain: 'crud-a8dfc.firebaseapp.com',
    databaseURL: 'https://crud-a8dfc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-a8dfc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtetWWNce0sB963Cso5guzyQ5Ee19itY',
    appId: '1:324767521440:android:b20fcddb004031cda187c5',
    messagingSenderId: '324767521440',
    projectId: 'crud-a8dfc',
    databaseURL: 'https://crud-a8dfc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-a8dfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8EDnGLw-h6_jWyTo8kt5C40okm9S9qn8',
    appId: '1:324767521440:ios:84456d6951473fefa187c5',
    messagingSenderId: '324767521440',
    projectId: 'crud-a8dfc',
    databaseURL: 'https://crud-a8dfc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-a8dfc.firebasestorage.app',
    iosBundleId: 'com.example.corehives',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8EDnGLw-h6_jWyTo8kt5C40okm9S9qn8',
    appId: '1:324767521440:ios:84456d6951473fefa187c5',
    messagingSenderId: '324767521440',
    projectId: 'crud-a8dfc',
    databaseURL: 'https://crud-a8dfc-default-rtdb.firebaseio.com',
    storageBucket: 'crud-a8dfc.firebasestorage.app',
    iosBundleId: 'com.example.corehives',
  );
}
